sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:  LTAI5tJ1dKEEzRHoxytDMkW4
    access-key-secret: aZVvqlGrKi4Re5CbHT15pt9ajpbxeD
    bucket-name: hzp-sky-take-out
  redis:
    host: localhost
    port: 6379
    password: 123456
    #redis自带了16个数据库 分别是0~15  默认数据库是0
    database: 10
  wechat:
    appid: wxf0487f65e7b9ffe4
    secret: 7dad3be3f289eaca09ee2372296efc7f